package org.brts.highlevel.template;

/*-
 * ===_LICENSE_BEGIN_===
 * BRTS — Blu-ray Tools Suite for authoring Blu-ray discs
 *
 * This file '/data/work/brts/brts-high-level/src/main/java/org/brts/highlevel/template/MovieDiscTemplate.java' is part of BRTS.
 * ==============================
 * Copyright (C) 2026 Pablo ABREU
 * ==============================
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-3.0.html>.
 * ===_LICENSE_END_===
 */

import org.brts.highlevel.descriptor.MovieDiscDescriptor;
import org.brts.middle.descriptor.DiscDescriptor;
import org.brts.middle.descriptor.TitleDescriptor;

import java.util.ArrayList;
import java.util.List;
import lombok.extern.slf4j.Slf4j;

/**
 * Template for a single-feature-film Blu-ray disc, with optional bonus tracks.
 * <p>
 * Title numbering:
 * <ul>
 * <li>Title 1 — main feature</li>
 * <li>Title 2, 3, … — bonus tracks in order</li>
 * </ul>
 * No top menu is generated by default (can be enabled in the descriptor).
 */
@Slf4j
public class MovieDiscTemplate implements DiscTemplate<MovieDiscDescriptor> {

	@Override
	public String templateType() {
		return "MOVIE";
	}

	@Override
	public DiscDescriptor expand(MovieDiscDescriptor descriptor) {
		log.info("Expanding MOVIE template: {}", descriptor.getDiscTitle());

		DiscDescriptor disc = new DiscDescriptor();
		disc.setDiscName(descriptor.getDiscTitle());
		disc.setHasTopMenu(false);

		List<TitleDescriptor> titles = new ArrayList<>();
		int titleId = 1;

		// Main feature
		if (descriptor.getMainFeature() != null) {
			TitleDescriptor main = toTitleDescriptor(titleId++, descriptor.getMainFeature());
			titles.add(main);
		}

		// Bonus tracks
		if (descriptor.getBonusTracks() != null) {
			for (MovieDiscDescriptor.MovieFeature bonus : descriptor.getBonusTracks()) {
				titles.add(toTitleDescriptor(titleId++, bonus));
			}
		}

		disc.setTitles(titles);
		return disc;
	}

	private TitleDescriptor toTitleDescriptor(int id, MovieDiscDescriptor.MovieFeature feature) {
		TitleDescriptor td = new TitleDescriptor();
		td.setTitleId(id);
		td.setSourceMkv(feature.getSourceMkv());
		td.setAudioLanguages(feature.getAudioLanguages());
		td.setSubtitleLanguages(feature.getSubtitleLanguages());
		// Default: single chapter at 00:00
		TitleDescriptor.ChapterMarker start = new TitleDescriptor.ChapterMarker();
		start.setTimeSeconds(0.0);
		td.setChapters(List.of(start));
		return td;
	}

}
